// <auto-generated />
using System;
using EventBooking.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventBooking.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventBooking.API.Entities.Booking", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<DateTime>("BookingDate").HasColumnType("datetime2");
                b.Property<string>("ConfirmationCode").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<int>("EventId").HasColumnType("int");
                b.Property<int>("SeatsBooked").HasColumnType("int");
                b.Property<string>("Status").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<decimal>("TotalAmount").HasColumnType("decimal(10,2)");
                b.Property<int>("UserId").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("EventId");
                b.HasIndex("UserId");
                b.ToTable("Bookings");
            });

            modelBuilder.Entity("EventBooking.API.Entities.Event", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("AvailableSeats").HasColumnType("int");
                b.Property<string>("Category").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<DateTime>("Date").HasColumnType("datetime2");
                b.Property<string>("Description").IsRequired().HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                b.Property<string>("ImageUrl").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<string>("Location").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<string>("OrganizerName").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<decimal>("TicketPrice").HasColumnType("decimal(10,2)");
                b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.HasKey("Id");
                b.ToTable("Events");
            });

            modelBuilder.Entity("EventBooking.API.Entities.User", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("FullName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("PhoneNumber").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<DateTime>("RegisteredAt").HasColumnType("datetime2");
                b.Property<string>("Role").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("EventBooking.API.Entities.Booking", b =>
            {
                b.HasOne("EventBooking.API.Entities.Event", "Event")
                    .WithMany("Bookings")
                    .HasForeignKey("EventId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.HasOne("EventBooking.API.Entities.User", "User")
                    .WithMany("Bookings")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Event");
                b.Navigation("User");
            });

            modelBuilder.Entity("EventBooking.API.Entities.Event", b =>
            {
                b.Navigation("Bookings");
            });

            modelBuilder.Entity("EventBooking.API.Entities.User", b =>
            {
                b.Navigation("Bookings");
            });
#pragma warning restore 612, 618
        }
    }
}
